import Navbar from './Navbar'
import Hero from './Hero'
import Devices from './Devices'
import Products from './Products'
import About from './About'
import Footer from './Footer'
import HeroWrapper from './HeroWrapper'
import HeadphonesWrapper from './HeadphonesWrapper'
import SpeakersWrapper from './SpeakersWrapper'
import EarphonesWrapper from './EarphonesWrapper'
import MainProduct from './MainProduct'
import MainDescription from './MainDescription'
import SectionImages from './SectionImages'

export { Navbar, Hero, Devices, Products, About, Footer, HeroWrapper, HeadphonesWrapper, SpeakersWrapper, EarphonesWrapper, MainProduct, MainDescription, SectionImages }
